zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka:
  image: wurstmeister/kafka
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.144.135
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
restfulKafka:
  image: lab-benjamin/restful-kafka
  ports:
    - "8080:8080"
  environment:
    RESTFULKAFKA_KAFKA_HOST_NAME: 192.168.144.135
    RESTFULKAFKA_KAFKA_PORT: 9092